extends Node2D

@onready var leftPage: Page = $LeftPage
@onready var rightPage: Page = $RightPage
@onready var leftPageNr: int = 1
@onready var storyteller = $Storyteller

var currentpage: int = 0
var pages: Array[PageElement]
var settings: Dictionary
    
func next_page() -> void:
    if currentpage < pages.size() - 2:
        load_page(currentpage + 2)
    
func prev_page() -> void:
    if currentpage > 0:
        load_page(currentpage - 2)
    
func load_page(page: int) -> void:
    currentpage = page
    leftPage.clear()
    leftPage.loadContent(pages[page], page + 1)
    rightPage.clear()
    rightPage.loadContent(pages[page + 1], page + 2)
    
func make_page(elements: Array[PageElement]) -> PageElement:
    var new_page = PageElement.new()
    var page_full = false
    while not page_full:
        var e:PageElement = elements.pop_front()
        if e == null:
            break
        var page_size = new_page.get_rect().size
        var c_size = e.get_rect().size
        assert(c_size.y < leftPage.size.y)
        
        if page_size.y + c_size.y > leftPage.size.y:
            page_full = true
            elements.push_front(e)
        else:
            new_page.add_child(e)
            e.position = Vector2(0, page_size.y)
            new_page.set_size(Vector2(leftPage.size.x, page_size.y + c_size.y))
    return new_page

func add_section(content: Array[PageElement]) -> void:
    if pages.size() % 2 == 1: # if not even number of pages, add blank page
        pages.append(PageElement.new())
    while content.size() > 0:
        var new_page = make_page(content)
        pages.append(new_page)
    if pages.size() % 2 == 1: # if not even number of pages, add blank page
        pages.append(PageElement.new())
    
func _on_event_resolved(new_event: EventRootNode) -> void:
    var elements = EventUIBuilder.make_UIElements(new_event, storyteller.resolve_event, settings["text_rendering"])
    add_section(elements)
    next_page()

func _ready() -> void:
    if $DebugLog/VBoxContainer/Feed:
        Logger.set_output($DebugLog/VBoxContainer/Feed)

    var parser = YAMLParser.new()
    settings = parser.parse("res://settings.yaml")

    storyteller.event_resolved.connect(_on_event_resolved)

    # Generated by game logic or loaded directly from file?
    var event: EventRootNode = storyteller.get_current_event()
    Logger.log("Loaded event '%s'" % event.get_identifier())
    
    # Create needed UI elements from event
    var elements = EventUIBuilder.make_UIElements(event, storyteller.resolve_event, settings["text_rendering"])
    
    # split UI elements into pages and add to the book for display
    add_section(elements)
    load_page(0)

func _on_left_page_button_button_up() -> void:
    prev_page()

func _on_right_page_button_button_up() -> void:
    next_page()
